# Generated by Django 4.2.4 on 2024-01-10 07:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_courses_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog')),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
