# Generated by Django 4.2.4 on 2024-01-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_carrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
                ('cv', models.FileField(upload_to='apply')),
            ],
        ),
    ]
